FROM node:24.18.0-alpine

WORKDIR /app

RUN npm install dotenv tsx zod

COPY apps/web/ apps/web/
COPY packages/ packages/
COPY package.json package.json

EXPOSE 3000

CMD ["node", "apps/web/front-server.js"]
